# Generated by Django 4.2.1 on 2026-04-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_alter_comments_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_gift_wrap',
            field=models.BooleanField(default=False),
        ),
    ]
