# Generated by Django 4.2.1 on 2026-04-15 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_product_is_gift_wrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_gift_wrap',
        ),
    ]
