# Generated by Django 4.2.1 on 2026-04-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='gift_wrap',
            field=models.CharField(blank=True, choices=[('', 'No Gift Wrap'), ('standard', 'Standard Gift Wrap (KSh 150)'), ('premium', 'Premium Gift Wrap (KSh 500)')], default='', max_length=10),
        ),
    ]
