# Generated by Django 4.2.1 on 2026-04-07 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_gift_wrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='gift_wrap',
        ),
    ]
